/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SUBSEAWIRELESS_PARAMETERS_PB_H_INCLUDED
#define PB_SUBSEAWIRELESS_PARAMETERS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _subseawireless_Parameter_identifier {
    subseawireless_Parameter_identifier_INVALID = 0,
    subseawireless_Parameter_identifier_manufacturer_name = 1,
    subseawireless_Parameter_identifier_swig_version_major = 2,
    subseawireless_Parameter_identifier_swig_version_minor = 129,
    subseawireless_Parameter_identifier_swig_type_major = 130,
    subseawireless_Parameter_identifier_swig_type_minor = 140,
    subseawireless_Parameter_identifier_device_type = 3,
    subseawireless_Parameter_identifier_comms_classification = 4,
    subseawireless_Parameter_identifier_power_classification = 131,
    subseawireless_Parameter_identifier_distance_classification = 132,
    subseawireless_Parameter_identifier_lateral_displacement = 133,
    subseawireless_Parameter_identifier_directivity = 134,
    subseawireless_Parameter_identifier_networking_capabilites = 135,
    subseawireless_Parameter_identifier_hardware_version = 5,
    subseawireless_Parameter_identifier_firmware_version = 6,
    subseawireless_Parameter_identifier_gtin = 7,
    subseawireless_Parameter_identifier_manufacturer_unique_identifier = 8,
    subseawireless_Parameter_identifier_product_name = 9,
    subseawireless_Parameter_identifier_max_input_power = 10,
    subseawireless_Parameter_identifier_min_input_voltage = 11,
    subseawireless_Parameter_identifier_max_input_voltage = 12,
    subseawireless_Parameter_identifier_max_design_output_power = 136,
    subseawireless_Parameter_identifier_min_output_voltage = 137,
    subseawireless_Parameter_identifier_max_output_voltage = 138,
    subseawireless_Parameter_identifier_max_supported_data_rate = 13,
    subseawireless_Parameter_identifier_max_tx_buffer_size = 14,
    subseawireless_Parameter_identifier_max_setpoint_wireless_power_delivery = 15,
    subseawireless_Parameter_identifier_requested_data_rate = 16,
    subseawireless_Parameter_identifier_current_data_rate = 17,
    subseawireless_Parameter_identifier_available_data_rates = 18,
    subseawireless_Parameter_identifier_max_rx_buffer_size = 19,
    subseawireless_Parameter_identifier_startup_power_config = 20,
    subseawireless_Parameter_identifier_status = 21,
    subseawireless_Parameter_identifier_error_code = 22,
    subseawireless_Parameter_identifier_uptime = 23,
    subseawireless_Parameter_identifier_internal_battery_state_of_charge = 24,
    subseawireless_Parameter_identifier_internal_battery_state_of_health = 139,
    subseawireless_Parameter_identifier_internal_temperature = 25,
    subseawireless_Parameter_identifier_Configuration = 26,
    subseawireless_Parameter_identifier_date_time = 27,
    subseawireless_Parameter_identifier_location = 28,
    subseawireless_Parameter_identifier_system_logs = 29,
    subseawireless_Parameter_identifier_logged_data = 30,
    subseawireless_Parameter_identifier_local_connection_configuration = 31,
    subseawireless_Parameter_identifier_gpio_state = 32,
    subseawireless_Parameter_identifier_comms_tx_power = 33,
    subseawireless_Parameter_identifier_comms_rx_gain = 34,
    subseawireless_Parameter_identifier_maximum_packet_size = 35,
    subseawireless_Parameter_identifier_buffer_size = 36,
    subseawireless_Parameter_identifier_mtu = 37,
    subseawireless_Parameter_identifier_wake_up_interval = 38,
    subseawireless_Parameter_identifier_inactivity_duration_before_sleep = 39,
    subseawireless_Parameter_identifier_wake_up_listen_duration = 40,
    subseawireless_Parameter_identifier_auto_gain_control = 41,
    subseawireless_Parameter_identifier_agc_compensation = 42,
    subseawireless_Parameter_identifier_average_noise_level = 43,
    subseawireless_Parameter_identifier_rssi = 44,
    subseawireless_Parameter_identifier_datarate = 45,
    subseawireless_Parameter_identifier_valid_packets_received = 46,
    subseawireless_Parameter_identifier_packets_lost = 47,
    subseawireless_Parameter_identifier_header_crc_error = 48,
    subseawireless_Parameter_identifier_payload_crc_error = 49,
    subseawireless_Parameter_identifier_fec_corrections = 50,
    subseawireless_Parameter_identifier_fec_failures = 51,
    subseawireless_Parameter_identifier_time_since_last_packet = 52,
    subseawireless_Parameter_identifier_time_since_counter_reset = 53,
    subseawireless_Parameter_identifier_background_light_level = 54,
    subseawireless_Parameter_identifier_background_noise = 55,
    subseawireless_Parameter_identifier_bytes_transmitted = 56,
    subseawireless_Parameter_identifier_bytes_received = 57,
    subseawireless_Parameter_identifier_save_config = 58,
    subseawireless_Parameter_identifier_reset_counters = 59,
    subseawireless_Parameter_identifier_clear_buffer = 60,
    subseawireless_Parameter_identifier_clear_log = 61,
    subseawireless_Parameter_identifier_send_data = 63,
    subseawireless_Parameter_identifier_received_data = 64,
    subseawireless_Parameter_identifier_tx_firmware = 66,
    subseawireless_Parameter_identifier_rx_firmware = 67,
    subseawireless_Parameter_identifier_protocol_mode = 68,
    subseawireless_Parameter_identifier_power_tx_input_power_limit = 69,
    subseawireless_Parameter_identifier_power_rx_output_power_limit = 70,
    subseawireless_Parameter_identifier_connection_timeout = 71,
    subseawireless_Parameter_identifier_default_event_interval = 72,
    subseawireless_Parameter_identifier_power_tx_power_levels = 73,
    subseawireless_Parameter_identifier_power_rx_power_levels = 74,
    subseawireless_Parameter_identifier_tx_signal_strength = 75,
    subseawireless_Parameter_identifier_rx_signal_strength = 76,
    subseawireless_Parameter_identifier_power_transfer_state = 77,
    subseawireless_Parameter_identifier_connection_state = 78,
    subseawireless_Parameter_identifier_connection_duration = 79,
    subseawireless_Parameter_identifier_power_tx_remote_power_output_enabled = 80,
    subseawireless_Parameter_identifier_power_rx_power_output_enabled = 81,
    subseawireless_Parameter_identifier_power_tx_input_current = 82,
    subseawireless_Parameter_identifier_power_rx_output_current = 83,
    subseawireless_Parameter_identifier_power_tx_input_voltage = 84,
    subseawireless_Parameter_identifier_power_rx_output_voltage = 85,
    subseawireless_Parameter_identifier_power_tx_max_input_current = 86,
    subseawireless_Parameter_identifier_power_rx_max_output_current = 87,
    subseawireless_Parameter_identifier_power_tx_max_input_voltage = 88,
    subseawireless_Parameter_identifier_power_rx_max_output_voltage = 89,
    subseawireless_Parameter_identifier_power_tx_foreign_object_detected = 90,
    subseawireless_Parameter_identifier_power_rx_foreign_object_detected = 91,
    subseawireless_Parameter_identifier_power_tx_max_temperature = 92,
    subseawireless_Parameter_identifier_power_rx_max_temperature = 93,
    subseawireless_Parameter_identifier_power_system_failure = 94,
    subseawireless_Parameter_identifier_power_tx_temperature = 95,
    subseawireless_Parameter_identifier_power_rx_temperature = 96,
    subseawireless_Parameter_identifier_power_tx_pressure = 97,
    subseawireless_Parameter_identifier_power_rx_pressure = 98,
    subseawireless_Parameter_identifier_read = 99,
    subseawireless_Parameter_identifier_write = 100,
    subseawireless_Parameter_identifier_event_reporting_interval = 101,
    subseawireless_Parameter_identifier_reset = 103,
    subseawireless_Parameter_identifier_temperature_2_3_4 = 104,
    subseawireless_Parameter_identifier_power_status = 105,
    subseawireless_Parameter_identifier_power_control_available = 106,
    subseawireless_Parameter_identifier_power_control_staus = 107,
    subseawireless_Parameter_identifier_schedule_network_for_shared_high_speed_usage = 108,
    subseawireless_Parameter_identifier_user_data_source_destinations_ack_required = 109,
    subseawireless_Parameter_identifier_source_destination_has_responding = 110,
    subseawireless_Parameter_identifier_announce_presence_for_ad_hoc_network = 111,
    subseawireless_Parameter_identifier_requested_local_id_grant = 112,
    subseawireless_Parameter_identifier_requested_local_id_deny = 113,
    subseawireless_Parameter_identifier_master_declaration_of_change_of_default_smac_modulator = 114,
    subseawireless_Parameter_identifier_declare_and_configure_node_as_a_relay = 115,
    subseawireless_Parameter_identifier_remove_node_as_relay = 116,
    subseawireless_Parameter_identifier_declare_and_configure_node_as_a_mesh_forwarder = 117,
    subseawireless_Parameter_identifier_remove_node_as_mesh_forwarder = 118,
    subseawireless_Parameter_identifier_reset_network = 119,
    subseawireless_Parameter_identifier_assign_timeslot = 120,
    subseawireless_Parameter_identifier_deassign_timeslot = 121,
    subseawireless_Parameter_identifier_csma_enable = 122,
    subseawireless_Parameter_identifier_allow_network_reset_if_control_lost = 124,
    subseawireless_Parameter_identifier_comms_capabilities = 125
} subseawireless_Parameter_identifier;

/* Struct definitions */
typedef struct _subseawireless_Parameter {
    subseawireless_Parameter_identifier id;
    bool boolean;
    int32_t integer;
    pb_callback_t string;
} subseawireless_Parameter;

typedef struct _subseawireless_Message {
    int32_t source;
    int32_t target;
    pb_callback_t requests; /* List of parameter IDs requested */
    pb_callback_t parameters; /* List of parameters sent */
    pb_callback_t responses; /* List of parameters sent as response */
} subseawireless_Message;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _subseawireless_Parameter_identifier_MIN subseawireless_Parameter_identifier_INVALID
#define _subseawireless_Parameter_identifier_MAX subseawireless_Parameter_identifier_swig_type_minor
#define _subseawireless_Parameter_identifier_ARRAYSIZE ((subseawireless_Parameter_identifier)(subseawireless_Parameter_identifier_swig_type_minor+1))

#define subseawireless_Parameter_id_ENUMTYPE subseawireless_Parameter_identifier



/* Initializer values for message structs */
#define subseawireless_Parameter_init_default    {_subseawireless_Parameter_identifier_MIN, 0, 0, {{NULL}, NULL}}
#define subseawireless_Message_init_default      {0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define subseawireless_Parameter_init_zero       {_subseawireless_Parameter_identifier_MIN, 0, 0, {{NULL}, NULL}}
#define subseawireless_Message_init_zero         {0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define subseawireless_Parameter_id_tag          1
#define subseawireless_Parameter_boolean_tag     2
#define subseawireless_Parameter_integer_tag     3
#define subseawireless_Parameter_string_tag      32
#define subseawireless_Message_source_tag        1
#define subseawireless_Message_target_tag        2
#define subseawireless_Message_requests_tag      3
#define subseawireless_Message_parameters_tag    4
#define subseawireless_Message_responses_tag     5

/* Struct field encoding specification for nanopb */
#define subseawireless_Parameter_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    id,                1) \
X(a, STATIC,   SINGULAR, BOOL,     boolean,           2) \
X(a, STATIC,   SINGULAR, INT32,    integer,           3) \
X(a, CALLBACK, SINGULAR, STRING,   string,           32)
#define subseawireless_Parameter_CALLBACK pb_default_field_callback
#define subseawireless_Parameter_DEFAULT NULL

#define subseawireless_Message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    source,            1) \
X(a, STATIC,   SINGULAR, INT32,    target,            2) \
X(a, CALLBACK, REPEATED, INT32,    requests,          3) \
X(a, CALLBACK, REPEATED, MESSAGE,  parameters,        4) \
X(a, CALLBACK, REPEATED, MESSAGE,  responses,         5)
#define subseawireless_Message_CALLBACK pb_default_field_callback
#define subseawireless_Message_DEFAULT NULL
#define subseawireless_Message_parameters_MSGTYPE subseawireless_Parameter
#define subseawireless_Message_responses_MSGTYPE subseawireless_Parameter

extern const pb_msgdesc_t subseawireless_Parameter_msg;
extern const pb_msgdesc_t subseawireless_Message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define subseawireless_Parameter_fields &subseawireless_Parameter_msg
#define subseawireless_Message_fields &subseawireless_Message_msg

/* Maximum encoded size of messages (where known) */
/* subseawireless_Parameter_size depends on runtime parameters */
/* subseawireless_Message_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
