/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "parameters.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(subseawireless_Parameter, subseawireless_Parameter, AUTO)


PB_BIND(subseawireless_Message, subseawireless_Message, AUTO)





