# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parameters.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10parameters.proto\x12\x0esubseawireless\"\xdb\x02\n\tParameter\x12\x30\n\x02id\x18\x01 \x01(\x0e\x32$.subseawireless.Parameter.identifier\x12\x0c\n\x04\x62ool\x18\x02 \x01(\x08\x12\x0f\n\x07integer\x18\x03 \x01(\x05\x12\x0e\n\x06string\x18  \x01(\t\"\xec\x01\n\nidentifier\x12\x0b\n\x07INVALID\x10\x00\x12\x15\n\x11manufacturer_name\x10\x01\x12\x1d\n\x19standard_compliance_major\x10\x02\x12\x1d\n\x19standard_compliance_minor\x10\x65\x12\x16\n\x12wet_interface_type\x10\x03\x12\x1a\n\x16\x62\x61\x63kground_light_level\x10\x36\x12\x14\n\x10\x62\x61\x63kground_noise\x10\x37\x12\x1a\n\x16transmitted_byte_count\x10\x38\x12\x16\n\x12save_configuration\x10:\"\x98\x01\n\x07Message\x12\x0e\n\x06source\x18\x01 \x01(\x05\x12\x0e\n\x06target\x18\x02 \x01(\x05\x12\x10\n\x08requests\x18\x03 \x03(\x05\x12-\n\nparameters\x18\x04 \x03(\x0b\x32\x19.subseawireless.Parameter\x12,\n\tresponses\x18\x05 \x03(\x0b\x32\x19.subseawireless.ParameterB\x1f\n\x1d\x63om.subseawireless.parametersb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parameters_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.subseawireless.parameters'
  _PARAMETER._serialized_start=37
  _PARAMETER._serialized_end=384
  _PARAMETER_IDENTIFIER._serialized_start=148
  _PARAMETER_IDENTIFIER._serialized_end=384
  _MESSAGE._serialized_start=387
  _MESSAGE._serialized_end=539
# @@protoc_insertion_point(module_scope)
